### PR TITLE
Test that the file input validation works

### LINKED ISSUE #13: It doesn't work when doesn't select file (React-hook-form V6)
https://github.com/satansdeer/rhf-validate-file/blob/ffe7946f7422adffe27dc5d25f9503c21ad7d178/src/App.js#L9

I also use this variant but it also doesn't work when doesn't select file:
```
     resume: Yup.mixed()
        .test('required', 'You need to provide a file', (value) => {
          return value.length > 0;
        })
        .test('fileSize', 'Size file more 100000 Byte', (value) => {
          return value && value[0].size < 100000;
        })
        .test('type', 'Add right type of file', (value) => {
          return value && availableMimeType.includes(value[0].type);
        }),
    });
```

### PR DESCRIPTION
**Pull request by satansdeer**
Write an acceptance test to verify that the file input indeed validates the empty file input.

Going to fix: #13

### CODE REVIEW

**Comment by satansdeer** [comment]
The issue is confirmed, probably will need to re-record the video

**Comment by satansdeer** [comment]
One problem is that the `picture` field is not going to be null, so the `required` validation rule is not going to be triggered.

The likely reason for this is that React Hook Form is always providing the value for the `file` input field. In the case of an empty file field, the value will be an empty `FileList`.

File: src/App.js [hunk 1]
```diff
@@ -4,29 +4,37 @@ import "./App.css";
...
 const schema = yup.object().shape({
-  picture: yup
-    .mixed()
+  picture: yup.mixed()
     .required("You need to provide a file")
-    .test("fileSize", "The file is too large", (value) => {
-      return value && value[0].size <= 2000000;
+    .test("fileSize", "The file is too large", function(value) {
+      console.log('*',value)
+      return false
```
Comment (satansdeer) [inline src/App.js:11]: I've tried to force the validation rule to return a validation error.

This resulted in an exception being thrown:
Screen Shot 2021-11-03 at 13 55 40


🤷‍♂️ 

I suspect that this might be a bug in React Hook Form. So I plan to update it.

**Comment by satansdeer** [comment]
Updated `yup` and `react-hook-form` packages. Not sure if it affected anything.

Fixed the validations by implementing a custom `test` to check that the file field has value.

**Comment by satansdeer** [comment]
Alright, now all the tests are passing.

I'll define a GitHub action to run the tests, so that the viewers could confirm that the app works.

**Comment by anurag472** [comment]
is this solved, can you show simpler example
